### ISSUE TITLE
Bluemix Car Demo Not working

### ISSUE THREAD

**Issue by techbm** [IBM-Blockchain/car-lease-demo#17]
Team,
This demo is no more working even the existing build and new builds are getting failed since last 3-4 days. Please help on fixing this.

Regards
PC

**Comment by jpayne23** [comment]
Hi PC,

The Car Lease Demo is to be used with the blockchain service on Bluemix. Unfortunately the service has been updated and the demo doesn't work on it anymore. In addition the service itself has been down since Friday.

We are currently working on fixing the demo and will let you know when it is ready.

Thanks

**Comment by techbm** [comment]
Thanks JP, Is there any timeline when it will up and running.

**Comment by kobigurk** [comment]
@jpayne23, I am able to run the blockchain locally - can you give more details about which commit to run?
I tried with several different commits (especially before Jun 9, when the Registrar struct was introduced), and failed.

**Comment by jpayne23** [comment]
The latest I have heard is they are going to roll back the updates so that a stable bluemix service is available, I have just tried to create a service and it not available at the moment but I have been told it will be running again shortly. 

When the service is up again the demo should run fine as it did last week, and I will post here when I am able to create a bluemix service again.

For running the demo locally, we are actively working on making the demo run with the same Hyperledger commit level that the blockchain bluemix service was going to use (3e0e80a898b259fe463295eabff80ee64f20695e) but we aren't there yet. Unfortunately we don't have any instructions for running locally as the bluemix blockchain and Hyperledger were very different but from the work we are doing now there should be some available next week.

**Comment by kobigurk** [comment]
Thanks! That clears things up and sounds awesome!

**Comment by gregmisiorek** [comment]
the issue seems to remain unresolved:
App/0
designed for a production environment, as it will leak
2016-07-25T10:07:28.360-0400
App/0
Warning: connect.session() MemoryStore is not
2016-07-25T10:07:28.360-0400
App/0
memory, and will not scale past a single process.
2016-07-25T10:07:28.360-0400

**Comment by awjh** [comment]
Hello @gregmisiorek,

It seems that the Bluemix blockchain service is still down at the minute so the app is unable to start up. This is causing the errors you've encountered. I am unsure when the service will resume but will update the issue when it does. If the service is rolled back then the demo will be running as soon as it starts up otherwise we will have to update it to work with the new service which will take longer.  

@jpayne23 is still working on getting it to run locally on the same commit level as we think an updated Bluemix service will be running.

**Comment by techbm** [comment]
Any updates on this track.

**Comment by mrshah-at-ibm** [comment]
Yes, a few updates.. The bluemix service is available now. With the new version of fabric, the user registration APIs have changed.. We are in the process of updating the car-lease demo to the SDK (aka HFC). It should be available in a day or two.

**Comment by f00bar** [comment]
Hello,

Any progress update on this ticket? It looks like the bluemix blockchain service is finally available now but the car lease demo still does not work.

Thanks.

**Comment by jpayne23** [comment]
Hello,

The bluemix service is now available again, it has been updated and some of those changes have caused the demo to not work anymore. We have been working on addressing these issues while the service has been down and fixed most of them, however there were some issues we were only able to work on with a functioning bluemix service so haven't quite fixed them yet.

The demo will be available soon and using the node SDK (HFC), we will let you know when we push the fixes.

Thanks

**Comment by awjh** [comment]
Hello,

The demo has now been run on Bluemix successfully with the code that was pushed yesterday. Some changes have been made to the way that it works:

**Chaincode:**
The new Bluemix service doesn't allow for chaincode to make https callouts. This means that the previous way of checking the user's ecert is no longer possible so chaincode now stores eCerts of all users passed to it during its deployment in the world state.

**Creating Users:**
The old user creation was making use of the loopback connector code. Now that HFC is available on Bluemix the demo has changed to make users using this. User creation is the only part that has been changed to use HFC the REST API is still used for all other calls to the Blockchain network.

**Running Locally**
The app has been modified to try and make it easier for users to run locally. It should now just require small changes to the configuration file. Instructions on how to do this will be added by the end of today.

**Comment by kobigurk** [comment]
@awjh @jpayne23 thanks for all your work! Waiting eagerly for the "Running Locally" section.
Meanwhile, I'm still having trouble to deploy. The "Deploying to Bluemix..." stage take a lot of time and eventually fails. Did you notice anything similar?

This is the end of the deployment log:
```

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 failing
FAILED
Start unsuccessful
```

**Comment by gregmisiorek** [comment]
App/0 at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/request/request.js:988:12)2016-08-10T09:01:22.297-0400
App/0 at Request.emit (events.js:129:20)2016-08-10T09:01:22.297-0400
App/0 at Request._callback (/home/vcap/app/Server_Side/blockchain/assets/vehicles/CRUD/create.js:73:17)2016-08-10T09:01:22.297-0400

**Comment by awjh** [comment]
The issues above I think relate to the Bluemix blockchain service not starting. We began noticing issues related to this last night and have been informed the service will be back up shortly.

I have now pushed the documentation with the installation guide for getting set up locally [here](/ibm-blockchain/car-lease-demo//tree/master/Documentation).

**Comment by kobigurk** [comment]
@awjh thanks! I haven't tried it yet. FYI, it works perfectly on bluemix now.
