### ISSUE TITLE
Vehicle Log Chaincode

### ISSUE THREAD

**Issue by f00bar** [IBM-Blockchain/car-lease-demo#19]
Hello,

There used to be an extra chaincode in this project called vehicle_log.go which used to keep track of the history that a vehicle goes through. This file is no longer part of the project so I'm just curious what's the current way of obtaining the steps that a particular vehicle went through during its lifecycle.

Thanks.

**Comment by awjh** [comment]
Hello, 

So the current process is that we read through every block on the blockchain to read the transactions within it. These transactions store the function call to the chaincode (e.g. create_vehicle) and the arguments passed as well as the caller. In a transfer one of the arguments is the identity of the new owner. 

Using this information we can build up the history of the vehicle using the function names as a guide as because we wrote the chaincode we know what the functions do in regards to the vehicle and the order of the arguments. The ledger.js file on client side can parse this information into the page and build up the image as it goes along so if a car is changed from red to blue the transactions before that change will refer to it as red and those after as blue until the colour is changed again.

To keep track of all the V5C IDs for when someone needs to request all the vehicles they own, rather than go through the blockchain to find all created we store in the chaincode an array of all the V5C IDs. The chaincode can then go through these pulling up the details and seeing if the caller has rights to read them.

**Comment by f00bar** [comment]
Thanks for the explaination. 

Was was the reasoning to move away from storing a history array in the chaincode to reading the blocks and transactions? How scalable is the new model? Is it general enough so that it could be used in other contexts for keeping track of change of custody / ownership of objects? Can you point me to place in the current chaincode where a query is being performed to obtain information about a vehicle's history?

Thanks!

**Comment by f00bar** [comment]
Hello,

Can anyone please explain the current method of obtaining the full history of a vehicle's life cycle?

**Comment by Jakeeyturner** [comment]
Hi @f00bar 

That's where you'll find the transaction data and can compile a history of vehicles: https://github.com/IBM-Blockchain/car-lease-demo/blob/master/Server_Side/blockchain/transactions/CRUD/read.js

Be sure to check this out also: https://github.com/IBM-Blockchain/car-lease-demo/blob/master/Documentation/API%20Methods.md#transactions
