### ISSUE TITLE
ID input for Car Lease doc

### ISSUE THREAD

**Issue by joshhus** [IBM-Blockchain/car-lease-demo#20]
Car lease demo doc ID input - sent details to @jpayne23 in email. 
e.g. is this a "lease"?
and this is from mfg. to scrap? 
The doc, at least, seems to only describe transfer of ownership. - sale. 
Don't see doc on lease or mfg. to scrap sequence.

**Comment by jpayne23** [comment]
Hi Josh,

Thanks a lot for the feedback.

The car lease demo is used to show the lifecycle of a vehicle. Currently this lifecycle includes creation, being manufactured, transfer between several different types of owners then being scrapped by a scrap merchant. At the moment there is no leasing of a vehicle, so we should definitely make this clearer in the docs.

We definitely need to go through the docs again to try and make it clearer for everyone, especially the details which are specific to the UK (e.g. V5C). We are updating the demo so that it works with the updated bluemix service so we will make these changes to the docs once we have pushed a working demo to this repository.

Thanks
