### ISSUE TITLE
Not sure why #17 got closed as the same error persists

### ISSUE THREAD

**Issue by gregmisiorek** [IBM-Blockchain/car-lease-demo#22]
App/0
designed for a production environment, as it will leak
2016-08-11T10:12:07.402-0400
App/0
memory, and will not scale past a single process.
2016-08-11T10:12:07.402-0400
App/0
Warning: connect.session() MemoryStore is not
2016-08-11T10:12:07.402-0400

**Comment by Jakeeyturner** [comment]
Hi @gregmisiorek,

It seems the Bluemix service still seems to be having problems still.
Apparently services are being created quicker than resources can be allocated.

I'll keep you updated of when Bluemix is fully functional and stable. The demo will also be updated in the near future to better the error messages and feedback/logs.

Thanks.

**Comment by gregmisiorek** [comment]
closing the issue doesn't exactly resolve it. the app is still clocking, but not sure why.

**Comment by Jakeeyturner** [comment]
Hi @gregmisiorek, apologies for closing this I thought I had responded.

The error you're seeing here isn't a serious problem. It's caused by https://github.com/IBM-Blockchain/car-lease-demo/blob/master/app.js#L318 when running on Bluemix but doesn't have any critical effect on the application.

Although it's only a warning, we will look into finding a way to suppress it from the logs.

If you have any other problems, feel free to let us know.
